// flow-typed signature: 00836fff8db7a55f5e4c385287f34216
// flow-typed version: <<STUB>>/webidl2_v^24.4.1/flow_v0.265.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webidl2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webidl2' {
  declare type IDLTree = Array<IDLProduction>;
  declare type IDLProduction = Object;

  declare module.exports: {
    parse: (string) => IDLTree,
    write: (IDLTree) => string,
  };
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
// declare module 'webidl2/dist/webidl2' {
//   declare module.exports: any;
// }

// declare module 'webidl2/lib/error' {
//   declare module.exports: any;
// }

// declare module 'webidl2/lib/productions/argument' {
//   declare module.exports: any;
// }

// declare module 'webidl2/lib/productions/array-base' {
//   declare module.exports: any;
// }

// declare module 'webidl2/lib/productions/attribute' {
//   declare module.exports: any;
// }

// declare module 'webidl2/lib/productions/base' {
//   declare module.exports: any;
// }

// declare module 'webidl2/lib/productions/callback-interface' {
//   declare module.exports: any;
// }

// declare module 'webidl2/lib/productions/callback' {
//   declare module.exports: any;
// }

// declare module 'webidl2/lib/productions/constant' {
//   declare module.exports: any;
// }

// declare module 'webidl2/lib/productions/constructor' {
//   declare module.exports: any;
// }

// declare module 'webidl2/lib/productions/container' {
//   declare module.exports: any;
// }

// declare module 'webidl2/lib/productions/default' {
//   declare module.exports: any;
// }

// declare module 'webidl2/lib/productions/dictionary' {
//   declare module.exports: any;
// }

// declare module 'webidl2/lib/productions/enum' {
//   declare module.exports: any;
// }

// declare module 'webidl2/lib/productions/extended-attributes' {
//   declare module.exports: any;
// }

// declare module 'webidl2/lib/productions/field' {
//   declare module.exports: any;
// }

// declare module 'webidl2/lib/productions/helpers' {
//   declare module.exports: any;
// }

// declare module 'webidl2/lib/productions/includes' {
//   declare module.exports: any;
// }

// declare module 'webidl2/lib/productions' {
//   declare module.exports: any;
// }

// declare module 'webidl2/lib/productions/interface' {
//   declare module.exports: any;
// }

// declare module 'webidl2/lib/productions/iterable' {
//   declare module.exports: any;
// }

// declare module 'webidl2/lib/productions/mixin' {
//   declare module.exports: any;
// }

// declare module 'webidl2/lib/productions/namespace' {
//   declare module.exports: any;
// }

// declare module 'webidl2/lib/productions/operation' {
//   declare module.exports: any;
// }

// declare module 'webidl2/lib/productions/token' {
//   declare module.exports: any;
// }

// declare module 'webidl2/lib/productions/type' {
//   declare module.exports: any;
// }

// declare module 'webidl2/lib/productions/typedef' {
//   declare module.exports: any;
// }

// declare module 'webidl2/lib/tokeniser' {
//   declare module.exports: any;
// }

// declare module 'webidl2/lib/validator' {
//   declare module.exports: any;
// }

// declare module 'webidl2/lib/validators/helpers' {
//   declare module.exports: any;
// }

// declare module 'webidl2/lib/validators/interface' {
//   declare module.exports: any;
// }

// declare module 'webidl2/lib/webidl2' {
//   declare module.exports: any;
// }

// declare module 'webidl2/lib/writer' {
//   declare module.exports: any;
// }

// // Filename aliases
// declare module 'webidl2/dist/webidl2.js' {
//   declare module.exports: $Exports<'webidl2/dist/webidl2'>;
// }
// declare module 'webidl2/index' {
//   declare module.exports: $Exports<'webidl2'>;
// }
// declare module 'webidl2/index.js' {
//   declare module.exports: $Exports<'webidl2'>;
// }
// declare module 'webidl2/lib/error.js' {
//   declare module.exports: $Exports<'webidl2/lib/error'>;
// }
// declare module 'webidl2/lib/productions/argument.js' {
//   declare module.exports: $Exports<'webidl2/lib/productions/argument'>;
// }
// declare module 'webidl2/lib/productions/array-base.js' {
//   declare module.exports: $Exports<'webidl2/lib/productions/array-base'>;
// }
// declare module 'webidl2/lib/productions/attribute.js' {
//   declare module.exports: $Exports<'webidl2/lib/productions/attribute'>;
// }
// declare module 'webidl2/lib/productions/base.js' {
//   declare module.exports: $Exports<'webidl2/lib/productions/base'>;
// }
// declare module 'webidl2/lib/productions/callback-interface.js' {
//   declare module.exports: $Exports<'webidl2/lib/productions/callback-interface'>;
// }
// declare module 'webidl2/lib/productions/callback.js' {
//   declare module.exports: $Exports<'webidl2/lib/productions/callback'>;
// }
// declare module 'webidl2/lib/productions/constant.js' {
//   declare module.exports: $Exports<'webidl2/lib/productions/constant'>;
// }
// declare module 'webidl2/lib/productions/constructor.js' {
//   declare module.exports: $Exports<'webidl2/lib/productions/constructor'>;
// }
// declare module 'webidl2/lib/productions/container.js' {
//   declare module.exports: $Exports<'webidl2/lib/productions/container'>;
// }
// declare module 'webidl2/lib/productions/default.js' {
//   declare module.exports: $Exports<'webidl2/lib/productions/default'>;
// }
// declare module 'webidl2/lib/productions/dictionary.js' {
//   declare module.exports: $Exports<'webidl2/lib/productions/dictionary'>;
// }
// declare module 'webidl2/lib/productions/enum.js' {
//   declare module.exports: $Exports<'webidl2/lib/productions/enum'>;
// }
// declare module 'webidl2/lib/productions/extended-attributes.js' {
//   declare module.exports: $Exports<'webidl2/lib/productions/extended-attributes'>;
// }
// declare module 'webidl2/lib/productions/field.js' {
//   declare module.exports: $Exports<'webidl2/lib/productions/field'>;
// }
// declare module 'webidl2/lib/productions/helpers.js' {
//   declare module.exports: $Exports<'webidl2/lib/productions/helpers'>;
// }
// declare module 'webidl2/lib/productions/includes.js' {
//   declare module.exports: $Exports<'webidl2/lib/productions/includes'>;
// }
// declare module 'webidl2/lib/productions/index' {
//   declare module.exports: $Exports<'webidl2/lib/productions'>;
// }
// declare module 'webidl2/lib/productions/index.js' {
//   declare module.exports: $Exports<'webidl2/lib/productions'>;
// }
// declare module 'webidl2/lib/productions/interface.js' {
//   declare module.exports: $Exports<'webidl2/lib/productions/interface'>;
// }
// declare module 'webidl2/lib/productions/iterable.js' {
//   declare module.exports: $Exports<'webidl2/lib/productions/iterable'>;
// }
// declare module 'webidl2/lib/productions/mixin.js' {
//   declare module.exports: $Exports<'webidl2/lib/productions/mixin'>;
// }
// declare module 'webidl2/lib/productions/namespace.js' {
//   declare module.exports: $Exports<'webidl2/lib/productions/namespace'>;
// }
// declare module 'webidl2/lib/productions/operation.js' {
//   declare module.exports: $Exports<'webidl2/lib/productions/operation'>;
// }
// declare module 'webidl2/lib/productions/token.js' {
//   declare module.exports: $Exports<'webidl2/lib/productions/token'>;
// }
// declare module 'webidl2/lib/productions/type.js' {
//   declare module.exports: $Exports<'webidl2/lib/productions/type'>;
// }
// declare module 'webidl2/lib/productions/typedef.js' {
//   declare module.exports: $Exports<'webidl2/lib/productions/typedef'>;
// }
// declare module 'webidl2/lib/tokeniser.js' {
//   declare module.exports: $Exports<'webidl2/lib/tokeniser'>;
// }
// declare module 'webidl2/lib/validator.js' {
//   declare module.exports: $Exports<'webidl2/lib/validator'>;
// }
// declare module 'webidl2/lib/validators/helpers.js' {
//   declare module.exports: $Exports<'webidl2/lib/validators/helpers'>;
// }
// declare module 'webidl2/lib/validators/interface.js' {
//   declare module.exports: $Exports<'webidl2/lib/validators/interface'>;
// }
// declare module 'webidl2/lib/webidl2.js' {
//   declare module.exports: $Exports<'webidl2/lib/webidl2'>;
// }
// declare module 'webidl2/lib/writer.js' {
//   declare module.exports: $Exports<'webidl2/lib/writer'>;
// }
