declare class EXT_texture_compression_bptc {
  static +COMPRESSED_RGB_BPTC_SIGNED_FLOAT_EXT: 0x8e8e;
  static +COMPRESSED_RGB_BPTC_UNSIGNED_FLOAT_EXT: 0x8e8f;
  static +COMPRESSED_RGBA_BPTC_UNORM_EXT: 0x8e8c;
  static +COMPRESSED_SRGB_ALPHA_BPTC_UNORM_EXT: 0x8e8d;
}
